services:

  deluged:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_deluged
    container_name: deluged
    volumes:
      - /mnt/torrents:/mnt/torrents
      - /var/lib/deluged:/var/lib/deluged
    ports:
      - 8112:8112
      - 6882:6882

  radarr:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_radarr
    container_name: radarr
    environment:
      - UMASK=002
    volumes:
      - /mnt/torrents:/mnt/torrents
      - /var/lib/radarr:/var/lib/radarr
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_sonarr
    container_name: sonarr
    environment:
      - UMASK=002
    volumes:
      - /mnt/torrents:/mnt/torrents
      - /var/lib/sonarr:/var/lib/sonarr
    ports:
      - 8989:8989
    restart: unless-stopped

  prowlarr:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_prowlarr
    container_name: prowlarr
    volumes:
      - /var/lib/prowlarr:/var/lib/prowlarr
    ports:
      - 9696:9696
    restart: unless-stopped

  overseerr:
    image: linuxserver/overseerr
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Madrid
      - PORT=5055
    ports:
      - 5055:5055
    volumes:
      - /var/lib/Overseerr:/config
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_nginx
    container_name: nginx
    ports:
      - 80:80

