services:
  deluged:
    build: 
      context: .
      dockerfile: dockerfiles/Dockerfile_deluged
      args:
        uid: 5000
        gid: 60000
    volumes:
      - data:/data
      - deluge_configs:/var/lib/deluged
    ports:
      - "8112:8112"

  radarr:
    build: 
      context: .
      dockerfile: dockerfiles/Dockerfile_radarr
      args:
        uid: 5001
        gid: 60000
    volumes:
      - data:/data
      - radarr_configs:/var/lib/radarr
    ports:
      - 7878:7878

  sonarr:
    build: 
      context: .
      dockerfile: dockerfiles/Dockerfile_sonarr
      args:
        uid: 5002
        gid: 60000
    volumes:
      - data:/data
      - sonarr_configs:/var/lib/sonarr
    ports:
      - 8989:8989

  prowlarr:
    build: 
      context: .
      dockerfile: dockerfiles/Dockerfile_prowlarr
      args:
        uid: 5003
        gid: 60000
    volumes:
      - prowlarr_configs:/var/lib/prowlarr
    ports:
      - 9696:9696

  overseerr:
    image: linuxserver/overseerr
    volumes:
      - overseerr_configs:/config
    ports:
      - 5055:5055

  nginx:
    build: 
      context: .
      dockerfile: dockerfiles/Dockerfile_nginx
    ports:
      - 80:80

volumes:
  deluge_configs:
  radarr_configs:
  prowlarr_configs:
  sonarr_configs:
  overseerr_configs:
  data:
