services:

  base_image:
    build:
      context: .
      dockerfile: dockerfiles/base_image
    image: base_image
    container_name: base_image

  radarr:
    build:
      context: .
      dockerfile: dockerfiles/radarr
      args:
        user: radarr
        group: media
        uid: 1000
        gid: 50000
        shell: /bin/bash
    container_name: radarr
    ports:
      - 7878:7878
    volumes:
      - radarr_configs:/var/lib/radarr
      - /mnt/torrents:/mnt/torrents
    depends_on:
      - base_image
    restart: unless-stopped

  sonarr:
    build:
      context: .
      dockerfile: dockerfiles/sonarr
      args:
        user: sonarr
        group: media
        uid: 1002
        gid: 50000
        shell: /bin/bash
    container_name: sonarr
    volumes:
      - /mnt/torrents:/mnt/torrents
      - sonarr_configs:/var/lib/sonarr
    ports:
      - 8989:8989
    depends_on:
      - base_image
    restart: unless-stopped

  prowlarr:
    build:
      context: .
      dockerfile: dockerfiles/prowlarr
      args:
        user: prowlarr
        group: media
        uid: 1003
        gid: 50000
        shell: /bin/bash
    container_name: prowlarr
    volumes:
      - prowlarr_configs:/var/lib/prowlarr
    ports:
      - 9696:9696

    depends_on:
      - base_image
    restart: unless-stopped

  overseerr:
    image: linuxserver/overseerr
    container_name: overseerr
    ports:
      - 5055:5055
    volumes:
      - overseerr_configs:/config
    restart: unless-stopped

  deluged:
    build:
      context: .
      dockerfile: dockerfiles/deluged
      args:
        user: deluged
        group: media
        uid: 1005
        gid: 50000
        shell: /bin/bash
    container_name: deluged
    volumes:
      - /mnt/torrents:/mnt/torrents
      - deluged_configs:/var/lib/deluged
    ports:
      - 8112:8112
      - 6882:6882
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z localhost 8112 && nc -z localhost 58846"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 5s
    depends_on:
      - base_image

  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - base_image
    depends_on:
      deluged:
        condition: service_healthy
    restart: unless-stopped

volumes:
  radarr_configs:
  sonarr_configs:
  prowlarr_configs:
  overseerr_configs:
  deluged_configs:
