FROM debian:bookworm-slim

RUN apt-get update && apt-get install nginx -y

WORKDIR /etc/nginx

COPY ./nginx/proxy_params .

COPY ./nginx/default ./sites-enabled/

ENTRYPOINT ["nginx"]

CMD ["-g","daemon off;"]
