FROM debian:bookworm-slim AS BUILD_IMAGE

WORKDIR /app

RUN apt-get update && apt-get install wget -y

RUN wget -q --content-disposition 'https://services.sonarr.tv/v1/download/main/latest?version=4&os=linux&arch=x64' && tar -xzf Sonarr*.linux*.tar.gz --strip-components=1

FROM debian:bookworm-slim

ARG user=sonarr
ARG group=media
ARG uid=5002
ARG gid=60000 
ARG shell=/bin/bash

RUN apt-get update && apt-get install curl sqlite3 libicu72 -y

RUN groupadd ${group} -g ${gid} && \ 
    useradd ${user} -m -u ${uid} -g ${group} -s ${shell} && \
    su -l ${user} -c 'echo "umask 002" >> ~/.bashrc' && \
    mkdir /opt/${user}

USER ${user}

WORKDIR /opt/${user}

COPY --from=BUILD_IMAGE /app ./

ENTRYPOINT ["./Sonarr"]

CMD ["-nobrowser","-data=/var/lib/sonarr/"]
