FROM debian:bookworm-slim

ARG user=deluged
ARG group=media
ARG uid=5000
ARG gid=60000
ARG shell=/bin/bash

RUN apt-get update && apt-get install deluged deluge-web supervisor -y 

COPY ./supervisord/${user}.conf /etc/supervisor/conf.d/

RUN groupadd ${group} -g ${gid} && \
    useradd ${user} -m -u ${uid} -g ${group} -s ${shell} && \
    su -l ${user} -c 'echo "umask 002" >> ~/.bashrc' && \
    chown 775 /var/lib/${user} -R && \
    chown ${user}:${group} /var/lib/${user} -R 

ENTRYPOINT ["supervisord"]

CMD ["-n","-c","/etc/supervisor/supervisord.conf"]
