FROM debian:bookworm-slim as BUILD_IMAGE

RUN apt-get update && apt-get install wget -y

WORKDIR /app

RUN wget -q --content-disposition 'http://radarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64' && tar -xzf Radarr*.linux*.tar.gz --strip-components=1

FROM debian:bookworm-slim

ARG user=radarr
ARG group=media
ARG uid=1000
ARG gid=50000
ARG shell=/bin/bash

RUN apt-get update && apt-get install curl sqlite3 libicu72 -y

RUN groupadd ${group} -g ${gid} && \
    useradd ${user} -m -u ${uid} -g ${group} -s ${shell} && \
    su -l ${user} -c 'echo "umask 0002" >> ~/.bashrc' && \
    mkdir /opt/${user}

USER ${user}

WORKDIR /opt/${user}

COPY --from=BUILD_IMAGE /app ./

ENTRYPOINT ["./Radarr"]

CMD ["-nobrowser","-data=/var/lib/radarr/"]
