FROM debian:bookworm-slim

ARG user=prowlarr
ARG group=media
ARG uid=5003
ARG gid=60000
ARG shell=/bin/bash

RUN apt-get update && apt-get install curl sqlite3 wget libicu72 -y

RUN groupadd ${group} -g ${gid} && \ 
    useradd ${user} -m -u ${uid} -g ${group} -s ${shell} && \
    su -l ${user} -c 'echo "umask 002" >> ~/.bashrc' && \
    mkdir /var/lib/${user} && \ 
    chown 775 /var/lib/${user} -R && \ 
    chown ${user}:${group} /var/lib/${user} -R && \
    mkdir /opt/${user}

WORKDIR /opt/${user}

RUN wget --content-disposition 'http://prowlarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64' && tar -xvzf Prowlarr*.linux*.tar.gz --strip-components=1

RUN chown ${user}:${group} /opt/${user} -R && chmod 775 /opt/${user} -R

USER ${user}

ENTRYPOINT ["./Prowlarr"]

CMD ["-nobrowser","-data=/var/lib/prowlarr/"]
